// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_XArX4DGlB-2--4Yg9s-fJbZ5RQ5Xtw',
    appId: '1:390858362212:web:264d7753d31c5af1dabe71',
    messagingSenderId: '390858362212',
    projectId: 'ehealth-7b319',
    authDomain: 'ehealth-7b319.firebaseapp.com',
    storageBucket: 'ehealth-7b319.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sQboXXXcS6_mfdJtvR-bgFsP8oy4R5E',
    appId: '1:390858362212:android:1e13c1b4d321c707dabe71',
    messagingSenderId: '390858362212',
    projectId: 'ehealth-7b319',
    storageBucket: 'ehealth-7b319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfjC1yUv2KxymxGMflP_fb45zo7-W4S8',
    appId: '1:390858362212:ios:82bed1559879f155dabe71',
    messagingSenderId: '390858362212',
    projectId: 'ehealth-7b319',
    storageBucket: 'ehealth-7b319.appspot.com',
    androidClientId: '390858362212-gg3tajb57qok0ueq96r3lf4iugtfi45k.apps.googleusercontent.com',
    iosClientId: '390858362212-0oihp89elbhddi2l9aat27juaft67rgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmfjC1yUv2KxymxGMflP_fb45zo7-W4S8',
    appId: '1:390858362212:ios:82bed1559879f155dabe71',
    messagingSenderId: '390858362212',
    projectId: 'ehealth-7b319',
    storageBucket: 'ehealth-7b319.appspot.com',
    androidClientId: '390858362212-gg3tajb57qok0ueq96r3lf4iugtfi45k.apps.googleusercontent.com',
    iosClientId: '390858362212-0oihp89elbhddi2l9aat27juaft67rgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn_XArX4DGlB-2--4Yg9s-fJbZ5RQ5Xtw',
    appId: '1:390858362212:web:bea061c2b80bcfabdabe71',
    messagingSenderId: '390858362212',
    projectId: 'ehealth-7b319',
    authDomain: 'ehealth-7b319.firebaseapp.com',
    storageBucket: 'ehealth-7b319.appspot.com',
  );

}